<?php 

/**
 * Implements hook_domain_batch().
 */
function domain_aap_custom_panes_domain_batch() {
  $batch = array();
  // Facebook body_html page.
  $batch['facebook_block'] = array(
    '#form' => array(
      '#title' => t('Facebook Block'),
      '#type' => 'textarea',
      '#size' => 80,
      //'#maxlength' => 255,
      '#description' => t('Facebook Block HTML of page. like: AamAadmiParty'),
      '#required' => TRUE,
    ),
    '#permission' => 'administer domains',
    '#domain_action' => 'custom',
    '#meta_description' => t('Edit Facebook Block HTML Values.'),
    '#data_type' => 'string',
    '#weight' => 0,
    '#group' => t('Facebook Block'),
    '#collapsed' => FALSE,
    '#update_all' => FALSE,
    '#module' => t('Domain AAP Custom Pane'),
    '#submit' => 'domain_custom_pane_batch_submit_facebook',
    '#lookup' => 'domain_custom_pane_batch_lookup_facebook',
  );
  // Twitter body_htmls page.
  $batch['twitter_block'] = array(
    '#form' => array(
      '#title' => t('Twitter Block'),
      '#type' => 'textarea',
      '#size' => 80,
      //'#maxlength' => 255,
      '#description' => t('Twitter Block HTML of page. like: AamAadmiParty'),
      '#required' => TRUE,
    ),
    '#permission' => 'administer domains',
    '#domain_action' => 'custom',
    '#meta_description' => t('Edit Twitter Block HTML Values.'),
    '#data_type' => 'string',
    '#weight' => 0,
    '#group' => t('Twitter Block'),
    '#collapsed' => FALSE,
    '#update_all' => FALSE,
    '#module' => t('Domain AAP Custom Pane'),
    '#submit' => 'domain_custom_pane_batch_submit_twitter',
    '#lookup' => 'domain_custom_pane_batch_lookup_twitter',
  );
  return $batch;
}

/**
 * twitter batch submit body_html.
 * @param $form_values
 */
function domain_custom_pane_batch_submit_twitter($form_values) {
  domain_aap_custom_panes_batch_update_values($form_values, 'twitter');
}

/**
 * twitter default value body_html.
 * @param $domain
 * @return String
 */
function domain_custom_pane_batch_lookup_twitter($domain) {
  $data = domain_custom_pane_batch_lookup($domain, 'twitter');
  if (empty($data)) {
    $data = '<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script><a class="twitter-timeline" href="https://twitter.com/AamAadmiParty" data-widget-id="352375736809693184" height = 550px>Tweets by @AamAadmiParty</a>';
  }
  return $data;
}

/**
 * facebook batch submit body_html.
 * @param $form_values
 */
function domain_custom_pane_batch_submit_facebook($form_values) {
  domain_aap_custom_panes_batch_update_values($form_values, 'facebook');
}

/**
 * facebook default value body_html.
 * @param $domain
 * @return String
 */
function domain_custom_pane_batch_lookup_facebook($domain) {
  //dpm($domain['domain_id']);
  $data = domain_custom_pane_batch_lookup($domain, 'facebook');
  if (empty($data)) {
    $data = '<iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2FAamAadmiParty&amp;width&amp;height=590&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=true&amp;show_border=true&amp;appId=607545139264444" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:550px;" allowTransparency="true"></iframe>';
  }
  return $data;
}

/**
 * get body_html value by domain and type from domain_aap_custom_panes table.
 * @param $domain
 * @param $type
 * @return String
 */
function domain_custom_pane_batch_lookup($domain, $type) {
  $data = db_query("SELECT body_html FROM {domain_aap_social_blocks} WHERE type = :type AND domain_id = :domain_id",
    array(':type' => $type, ':domain_id' => $domain['domain_id']))->fetchField();
  return $data;
}

/**
 * update values in domain_aap_social_blocks.
 * @param $form_values
 * @param $type
 */
function domain_aap_custom_panes_batch_update_values($form_values, $type) {
  foreach ($form_values['domain_batch'] as $key => $body_html) {
    $_domain = domain_load($key);
    $data = domain_custom_pane_batch_lookup($_domain, $type);
    // Update if data exists
    if (!empty($data)) {
      db_update('domain_aap_social_blocks')
      ->fields(array('body_html' => $body_html))
      ->condition('domain_id', $key)
      ->condition('type', $type)
      ->execute();
    }
    // Insert if data doesn't exists.
    else {
      db_insert('domain_aap_social_blocks')
      ->fields(array(
      'domain_id' => $key,
      'type' => $type,
      'body_html' => $body_html,
      ))->execute();
    }
  }
}

/**
 * get content for facebook pane.
 * @return string
 */
function domain_aap_custom_panes_facebook_content() {
  $_domain = domain_get_domain();
  $body_html = domain_custom_pane_batch_lookup_facebook($_domain);
  return $body_html;
}

/**
 * get content for twitter pane.
 * @return string
 */
function domain_aap_custom_panes_twitter_content() {
  $_domain = domain_get_domain();
  $body_html = domain_custom_pane_batch_lookup_twitter($_domain);
  return $body_html;
}

/**
 * Implements hook_node_access().
 * @param $node
 * @param $op
 * @param $account
 * @return string
 */
function domain_aap_custom_panes_node_access($node, $op, $account) {
  if (isset($node->domain_source) && isset($account->domain_user)) {
    switch ($op) {
      case 'update':
        if (in_array($node->domain_source, $account->domain_user) &&
        user_access('edit any content directly owned by assigned domain', $account)) {
          return NODE_ACCESS_ALLOW;
        }
        break;
      case 'delete':
        if (in_array($node->domain_source, $account->domain_user) &&
        user_access('delete any content directly owned by assigned domain', $account)) {
          return NODE_ACCESS_ALLOW;
        }
        break;
    }
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_permissions();
 * @return array
 */
function domain_aap_custom_panes_permission()  {
  return array(
    'edit any content directly owned by assigned domain' => array(
      'title' => t('edit any content directly owned by assigned domain'),
      'description' => t('Edit any content owned by assigned domain')),
    'delete any content directly owned by assigned domain' => array(
      'title' => t('delete any content directly owned by assigned domain'),
      'description' => t('Delete any content owned by assigned domain')),
  );
}

