<?php

/**
 * Implements hook_domain_batch().
 */
function domain_aap_custom_panes_domain_batch() {
  $batch = array();
  // Facebook body_html page.
  $batch['facebook_block'] = array(
    '#form' => array(
      '#title' => t('Facebook Block'),
      '#type' => 'textarea',
      '#size' => 80,
      //'#maxlength' => 255,
      '#description' => t('Facebook Block HTML of page. like: AamAadmiParty'),
      '#required' => TRUE,
    ),
    '#permission' => 'administer domains',
    '#domain_action' => 'custom',
    '#meta_description' => t('Edit Facebook Block HTML Values.'),
    '#data_type' => 'string',
    '#weight' => 0,
    '#group' => t('Facebook Block'),
    '#collapsed' => FALSE,
    '#update_all' => FALSE,
    '#module' => t('Domain AAP Custom Pane'),
    '#submit' => 'domain_custom_pane_batch_submit_facebook',
    '#lookup' => 'domain_custom_pane_batch_lookup_facebook',
  );
  // Twitter body_htmls page.
  $batch['twitter_block'] = array(
    '#form' => array(
      '#title' => t('Twitter Block'),
      '#type' => 'textarea',
      '#size' => 80,
      //'#maxlength' => 255,
      '#description' => t('Twitter Block HTML of page. like: AamAadmiParty'),
      '#required' => TRUE,
    ),
    '#permission' => 'administer domains',
    '#domain_action' => 'custom',
    '#meta_description' => t('Edit Twitter Block HTML Values.'),
    '#data_type' => 'string',
    '#weight' => 0,
    '#group' => t('Twitter Block'),
    '#collapsed' => FALSE,
    '#update_all' => FALSE,
    '#module' => t('Domain AAP Custom Pane'),
    '#submit' => 'domain_custom_pane_batch_submit_twitter',
    '#lookup' => 'domain_custom_pane_batch_lookup_twitter',
  );
  // Logo change page.
  $batch['domain_logo'] = array(
    '#form' => array(
      '#title' => t('Domain specific Logo'),
      '#type' => 'managed_file',
      //'#size' => 80,
      //'#maxlength' => 255,
      '#description' => t('Choose an image file to upload.'),
      '#required' => FALSE,
      '#upload_validators' => array(
        'file_validate_extensions' => array('png jpg jpeg gif'),
      ),
      '#upload_location' => 'public://domain_logo/',
    ),
    '#permission' => 'administer domains',
    '#domain_action' => 'custom',
    '#meta_description' => t('Different logo for different domains. If there is no image then, default logo of the theme will be used. Height of the image will be resized to 47px.'),
    '#data_type' => 'string',
    '#weight' => 0,
    '#group' => t('Domain specific Logo'),
    '#collapsed' => FALSE,
    '#update_all' => FALSE,
    '#module' => t('Domain AAP Custom Pane'),
    '#submit' => 'domain_custom_pane_batch_submit_logo',
    '#lookup' => 'domain_custom_pane_batch_lookup_logo',
  );
  return $batch;
}

/**
 * submit handler for domain logo
 * @param $form_values
 */
function domain_custom_pane_batch_submit_logo($form_values) {
  foreach ($form_values['domain_batch'] as $key => $file_fid) {
    $_domain = domain_load($key);
    // get if there is already data in the table for given domain.
    $data = domain_custom_pane_batch_lookup_logo($_domain);
    if (!empty($file_fid)) {
      $file = file_load($file_fid);
      // making the file status permanent
      $file->status = 1;
      $file = file_save($file);
    }
    // check if fid exists.
    // explicit check of 0 because empty returns true for 0.
    if (!empty($data) || $data === '0') {
      db_update('domain_aap_logo_uri')
      ->fields(array('image_fid' => $file_fid))
      ->condition('domain_id', $key)
      ->execute();
    }
    else {
      // Insert if data doesn't exists.
      db_insert('domain_aap_logo_uri')
      ->fields(array(
      'domain_id' => $key,
      'image_fid' => $file_fid,
      ))->execute();
    }
  }
}

/**
 * get domain logo inage file fid from domain
 * @param $domain
 * @return int FID
 */
function domain_custom_pane_batch_lookup_logo($domain) {
  $data = db_query("SELECT image_fid FROM {domain_aap_logo_uri} WHERE domain_id = :domain_id",
    array(':domain_id' => $domain['domain_id']))->fetchField();
  return $data;
}

/**
 * twitter batch submit body_html.
 * @param $form_values
 */
function domain_custom_pane_batch_submit_twitter($form_values) {
  domain_aap_custom_panes_batch_update_values($form_values, 'twitter');
}

/**
 * twitter default value body_html.
 * @param $domain
 * @return String
 */
function domain_custom_pane_batch_lookup_twitter($domain) {
  $data = domain_custom_pane_batch_lookup($domain, 'twitter');
  if (empty($data)) {
    $data = '<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script><a class="twitter-timeline" href="https://twitter.com/AamAadmiParty" data-widget-id="352375736809693184" height = 550px>Tweets by @AamAadmiParty</a>';
  }
  return $data;
}

/**
 * facebook batch submit body_html.
 * @param $form_values
 */
function domain_custom_pane_batch_submit_facebook($form_values) {
  domain_aap_custom_panes_batch_update_values($form_values, 'facebook');
}

/**
 * facebook default value body_html.
 * @param $domain
 * @return String
 */
function domain_custom_pane_batch_lookup_facebook($domain) {
  //dpm($domain['domain_id']);
  $data = domain_custom_pane_batch_lookup($domain, 'facebook');
  if (empty($data)) {
    $data = '<iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2FAamAadmiParty&amp;width&amp;height=590&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=true&amp;show_border=true&amp;appId=607545139264444" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:550px;" allowTransparency="true"></iframe>';
  }
  return $data;
}

/**
 * get body_html value by domain and type from domain_aap_custom_panes table.
 * @param $domain
 * @param $type
 * @return String
 */
function domain_custom_pane_batch_lookup($domain, $type) {
  $data = db_query("SELECT body_html FROM {domain_aap_social_blocks} WHERE type = :type AND domain_id = :domain_id",
    array(':type' => $type, ':domain_id' => $domain['domain_id']))->fetchField();
  return $data;
}

/**
 * update values in domain_aap_social_blocks.
 * @param $form_values
 * @param $type
 */
function domain_aap_custom_panes_batch_update_values($form_values, $type) {
  foreach ($form_values['domain_batch'] as $key => $body_html) {
    $_domain = domain_load($key);
    $data = domain_custom_pane_batch_lookup($_domain, $type);
    // Update if data exists
    if (!empty($data)) {
      db_update('domain_aap_social_blocks')
      ->fields(array('body_html' => $body_html))
      ->condition('domain_id', $key)
      ->condition('type', $type)
      ->execute();
    }
    // Insert if data doesn't exists.
    else {
      db_insert('domain_aap_social_blocks')
      ->fields(array(
      'domain_id' => $key,
      'type' => $type,
      'body_html' => $body_html,
      ))->execute();
    }
  }
}

/**
 * get content for facebook pane.
 * @return string
 */
function domain_aap_custom_panes_facebook_content() {
  $_domain = domain_get_domain();
  $body_html = domain_custom_pane_batch_lookup_facebook($_domain);
  return $body_html;
}

/**
 * get content for twitter pane.
 * @return string
 */
function domain_aap_custom_panes_twitter_content() {
  $_domain = domain_get_domain();
  $body_html = domain_custom_pane_batch_lookup_twitter($_domain);
  return $body_html;
}

