<?php
/**
 * @file
 * A module which provides a redirection service for mobile devices
 */

define('MOBILE_SITE', 'http://m.aamaadmiparty.org');

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function mredirect_help($path, $arg) {
  switch($path) {
    case "admin/help#mredirect":
      return '<p>' . t("Provides a redirection service for mobile devices. It redirects using the DeviceAtlas 
          redirection service").'</p>';
    break;
  }
}

/*
 * Implementation of hook_boot
 */

function mredirect_boot() {
  require_once 'includes/common.inc';
  header('Vary: User-Agent');
  
  drupal_add_js('http://detect.deviceatlas.com/redirect.js?m=' . MOBILE_SITE . '&t=false', 'external');
  drupal_add_html_head_link(array(
    "rel" => "alternate",
    "media" => "only screen and (max-width: 640px)",
    "href" => MOBILE_SITE."/w/".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']
  ));
}
