<?php
/**
 * @file
 * A module which provides a redirection service for mobile devices
 */

define('MOBILE_SITE', 'http://m.aamaadmiparty.org');

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function mredirect_help($path, $arg) {
  switch($path) {
    case "admin/help#mredirect":
      return '<p>' . t("Provides a redirection service for mobile devices. It redirects using the DeviceAtlas redirection service").'</p>';
    break;
  }
}

/*
 * Implementation of hook_boot
 */

function mredirect_boot() {
	require_once 'includes/common.inc';
	drupal_add_js('http://detect.deviceatlas.com/redirect.js?m=' . MOBILE_SITE . '&t=false', 'external');

	$element = array(
		'#tag' => 'link', // The #tag is the html tag - <link />
		'#attributes' => array( // Set up an array of attributes inside the tag
			'href' => MOBILE_SITE,
			'rel' => 'alternate',
			'media' => 'handheld',
		),
	);
	drupal_add_html_head($element, 'google_mobile_seo_link');
}
